version: '3.5'
services:
  discordrolebot:
   #build:
   #   context: ./
    image: acocalypso/discordrolemanager:latest 
    ports:
      - "9000:9000"
    volumes:
      - ./config/:/usr/src/app/config/
      - ./locale/:/usr/src/app/locale/